# Nixpacks configuration for Railway
# Forces Railway to use Nixpacks instead of Docker

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit || npm install"]

[phases.build]
cmds = ["npm run build --if-present"]

[start]
cmd = "npm start"
